### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by michalmela** [skjolber/jackson-syntax-highlight#1]
Hi @skjolber 

First of all, congratulations on a great little module!

Would you mind adding a license file?

I am specifically interested if it's OK to just slurp your classes right into my project to reduce dependencies and risks when updating Jackson independently of the `jackson-syntax-highlight`.

**Comment by skjolber** [comment]
Thanks!

I've referenced the Apache license in the readme and now also there is a concrete Apache License 2.0 LICENSE file in the repo. 

Yeah, go ahead and slurp, there have been some jackson security issues lately and as a lone developer updates are a bit random.
