### ISSUE TITLE
Syntax highlighting with ObjectMapper

### ISSUE THREAD

**Issue by xnbox** [skjolber/jackson-syntax-highlight#20]
Hi Thomas,
I like your idea of highlighting syntax while generating with Jackson.
I would like to implement JSON ANSI syntax highlighting in my project [DeepfakeHTTP](https://github.com/xnbox/DeepfakeHTTP).

Currently, I generate JSON string from Map in this form:
```java
Map<String, Object> map = ...
...
ObjectMapper om = new ObjectMapper(new JsonFactory());
String json = om.writeValueAsString(map);
```
I don't generate the JSON with <code>JsonGenerator</code>, so I can't use **jackson-syntax-highlight** directly because it's <code>JsonGenerator</code>.
Is there any way to work around this limitation?

Thanks!

**Comment by xnbox** [comment]
I found a solution.
<code>JsonGenerator</code> has a method <code>writeObject()</code> that generates JSON for the whole object.
Maybe someone else will find it useful:

```java
JsonGenerator jsonGenerator = new SyntaxHighlightingJsonGenerator(delegate, highlighter, prettyprint);
jsonGenerator.writeObject(obj);
```

Everything works now, thanks!

P.S. Added **jackson-syntax-highlight** to the third-party list of my project.

**Comment by skjolber** [comment]
@xnbox thanks, I've added this to the readme. Note that default colors now have been removed.
